const rows={
 noNext:['이번 방문 자율 검토 종료/중지','Automatic review finished/stopped for this visit','今回の自動検討は終了・停止'],
 specialty:['전문 상품: {item}','Specialty: {item}','専門商品: {item}'],next:['다음 자율 검토: {time}','Next automatic review: {time}','次の自動検討: {time}'],available:['마을 가용 재고: {items}','Available village stock: {items}','村の利用可能在庫: {items}'],
 stale:['견적이 만료되거나 재고가 바뀌었습니다. 다시 지시해 주세요.','Quote expired or stock changed. Please order again.','見積期限切れまたは在庫変更。再度指示してください。'],
 title:['방문 상인','Visiting merchant','訪問商人'],empty:['방문 상인이 없습니다.','No visiting merchant.','訪問商人はいません。'],closed:['거래를 마치고 떠났습니다.','The merchant has departed.','商人は出発しました。'],
 depart:['출발까지 {time}','Leaves in {time}','出発まで {time}'],auto:['자율 거래 · 예산 {budget} / 사용 {spent}','Auto trade · budget {budget} / spent {spent}','自動取引 · 予算 {budget} / 使用 {spent}'],stopped:['이번 방문 자율 거래 중지','Auto trade stopped for this visit','今回の自動取引は停止中'],
 reserves:['비축 보호: {items}','Protected reserves: {items}','備蓄保護: {items}'],forbidden:['판매 금지: {items}','Never sell: {items}','売却禁止: {items}'],cash:['상인 보유 은 {amount}','Merchant silver {amount}','商人の銀 {amount}'],prices:['구매 {buy} / 판매 {sell}','Buy {buy} / sell {sell}','購入 {buy} / 売却 {sell}'],automatic:['자율','Automatic','自動'],manual:['지시','Ordered','指示'],
 help:['채팅: 식량 10 구매 · 나무 10 판매 · 약초 판매 금지 · 나무 30 비축 · 거래 예산 5 · 거래 중지. 도착 20초 후 자율 거래를 검토합니다.','Chat: buy food 10 · sell wood 10 · never sell herbs · reserve wood 30 · trade budget 5 · stop trading. Auto trade starts after 20 game seconds.','チャット: 食料 10 購入 · 木材 10 売却 · 薬草を売らない · 木材 30 備蓄 · 取引予算 5 · 取引停止。到着20秒後に自動取引を検討します。'],
 done:['거래 완료 · 은 변화 {silver}. 거래 현황에서 품목별 결과를 볼 수 있습니다.','Trade complete · silver change {silver}. See trade status for items.','取引完了 · 銀の変化 {silver}。取引状況で明細を確認できます。'],policySaved:['이번 상인의 거래 방침을 바꿨습니다.','Policy updated for this visit.','今回の取引方針を更新しました。'],
 unavailable:['거래 가능한 상인이 없습니다.','No merchant available to trade.','取引できる商人がいません。'],expired:['해당 상인은 이미 떠났습니다.','That merchant has left.','その商人は出発しました。'],duplicate:['이미 처리한 거래입니다.','Trade already processed.','処理済みの取引です。'],limit:['이번 방문의 거래 횟수 한도입니다.','Visit transaction limit reached.','今回の取引上限です。'],invalid:['품목·수량·거래 조건을 확인해 주세요.','Check the items, quantities and conditions.','品目・数量・条件を確認してください。'],stock:['요청 수량만큼 재고가 없습니다.','Insufficient stock for the full order.','指定数量の在庫がありません。'],capacity:['보관 공간이 부족합니다.','Not enough storage capacity.','保管容量が不足しています。'],reserve:['비축량 또는 판매 금지 방침을 위반합니다.','This would break a reserve or selling rule.','備蓄または売却禁止の方針に反します。'],money:['은 또는 지정 예산이 부족합니다.','Insufficient silver or budget.','銀または予算が不足しています。']};
export const tradeCatalogs=Object.fromEntries(['ko','en','ja'].map((locale,i)=>[locale,Object.fromEntries(Object.entries(rows).map(([key,values])=>[`trade.${key}`,values[i]]))]));
