import assert from 'node:assert/strict';
import { Camera } from '../src/game/Camera.js';
import { CameraTour } from '../src/game/CameraTour.js';

const camera = new Camera();
camera.resize(640, 480);
const home = { x: 1000, y: 1000 };
const entry = { x: 1022, y: 1000 };
camera.center(home);
const tour = new CameraTour();
assert.ok(tour.start('raid-1', entry, home, camera));
for (let i = 0; i < 7; i++) tour.update(100, camera);
assert.equal(camera.x, entry.x - camera.width / 2);
assert.equal(tour.current.stage, 'watching');
for (let i = 0; i < 25; i++) tour.update(100, camera);
assert.equal(tour.current.stage, 'returning');
for (let i = 0; i < 7; i++) tour.update(100, camera);
assert.equal(tour.current, null);
assert.equal(camera.x, home.x - camera.width / 2);
assert.equal(tour.start('raid-1', entry, home, camera), false, 'one introduction per raid');
tour.start('raid-2', entry, home, camera);
tour.update(200, camera);
tour.cancel();
camera.pan(-3, 0);
const manual = camera.x;
tour.update(5000, camera);
assert.equal(camera.x, manual, 'manual panning must not snap back later');
assert.equal(tour.start('raid-3', entry, home, camera, { reducedMotion: true }), false);
assert.equal(tour.start('raid-4', entry, home, camera, { enabled: false }), false);
assert.equal(camera.x, manual);
tour.start('raid-5', { x: 1999, y: 0 }, home, camera);
for (let i = 0; i < 10; i++) tour.update(100, camera);
assert.ok(camera.x + camera.width <= 2000 && camera.y >= 0);
console.log('cameraTour: passed');
