import assert from 'node:assert/strict';
import { createInitialWorld } from '../src/game/World.js';
import { Factions } from '../src/game/Factions.js';
import { DiplomacySystem, proposeDiplomacy, respondCounteroffer, applyBattleConsequences } from '../src/game/Diplomacy.js';
const world=createInitialWorld();new Factions(world);const system=new DiplomacySystem(world);
const home=world.getVillage('home'), faction=world.state.factions[0];home.food=100;home.silver=10;
faction.stance='hostile';faction.strength=90;faction.resources.food=100;
assert.equal(proposeDiplomacy(world,'truce',faction.id).ok,true);
assert.equal(faction.stance,'hostile');
assert.equal(proposeDiplomacy(world,'truce',faction.id).ok,false);
world.state.time=20;system.update();assert.equal(world.state.diplomacy.proposals[0].status,'counteroffer');assert.equal(home.food,96);
assert.equal(respondCounteroffer(world,'proposal-1',false).ok,true);assert.equal(home.food,100);
assert.equal(respondCounteroffer(world,'proposal-1',false).ok,false);assert.equal(home.food,100);
faction.strength=20;assert.equal(proposeDiplomacy(world,'truce',faction.id).ok,true);
world.state.time=40;system.update();assert.equal(faction.stance,'neutral');assert.equal(home.food,96);
const plan={sourceFactionId:faction.id};const combat={units:[{side:'enemy',hp:0}],breachPressure:2};
applyBattleConsequences(world,plan,combat);const strength=faction.strength;applyBattleConsequences(world,plan,combat);assert.equal(faction.strength,strength);
assert.ok([...world.state.buildings.values()].some(b=>b.damage>0));
faction.stance='hostile';faction.strength=90;faction.resources.food=100;
assert.equal(proposeDiplomacy(world,'truce',faction.id).ok,true);world.state.time=60;system.update();
const counter=world.state.diplomacy.proposals.find(p=>p.status==='counteroffer');home.silver=2;
assert.equal(respondCounteroffer(world,counter.id,true).ok,false);assert.equal(faction.stance,'hostile');
home.silver=3;assert.equal(respondCounteroffer(world,counter.id,true).ok,true);assert.equal(home.silver,0);assert.equal(faction.stance,'neutral');
assert.equal(respondCounteroffer(world,counter.id,true).ok,false);
console.log('diplomacy: passed');
