import assert from 'node:assert/strict';
import { createInitialWorld } from './fixtures/legacyWorld.mjs';
import { foodBalance, tick } from '../src/game/Simulation.js';
import { getWorldNeeds } from '../src/game/WorldNeeds.js';
import { executeDivineAction } from '../src/actions/divineActions.js';
import { executeWorldAction } from '../src/actions/worldActions.js';

const world = createInitialWorld();
const south = world.getVillage('south');
assert.equal(south.farmCount, 5);
assert.equal(south.houseCount, 4);
assert.ok(Math.abs(foodBalance(south).production - 7.2) < 1e-9);
assert.equal(getWorldNeeds(world.state).some(n => n.villageId === 'south' && n.type === 'food_shortage'), true);
const startFood = south.food;
tick(world.state);
assert.equal(south.food, startFood - 4);
const structure = { actor: 'south', target: 'south', action: 'farm', reason: 'food_shortage', parameters: {} };
executeWorldAction(world, structure);
executeWorldAction(world, structure);
assert.equal(south.farmCount, 7);
executeDivineAction(world, { status: 'understood', action: 'create_rain', target: 'south', parameters: {} });
assert.ok(foodBalance(south).production > foodBalance(south).consumption);
assert.equal(getWorldNeeds(world.state).some(n => n.villageId === 'south'), false);
south.farmCount = 0;
south.food = 0;
tick(world.state);
assert.equal(south.population, 109);
assert.equal(south.food, 0);
assert.ok(getWorldNeeds(world.state).some(n => n.type === 'food_shortage'));
console.log('economy: passed');
