import assert from 'node:assert/strict';
import { createInitialWorld } from '../src/game/World.js';
import { Factions } from '../src/game/Factions.js';
import { WorkSystem } from '../src/game/Work.js';
import { LivingWorld, tradeWithCaravan, protectHerd } from '../src/game/LivingWorld.js';
const world=createInitialWorld();new Factions(world);new WorkSystem(world);const life=new LivingWorld(world), home=world.getVillage('home');
world.state.time=240;life.update();assert.equal(world.state.life.caravan.stage,'forecast');assert.equal(tradeWithCaravan(world,'sheep').ok,false);
const source=world.state.factions.find(f=>f.id===world.state.life.caravan.source),reservedFood=source.resources.food,reservedSheep=source.resources.sheep;
world.state.time=360;life.update();home.silver=20;assert.equal(tradeWithCaravan(world,'sheep').ok,true);assert.equal(world.state.life.sheep,1);
world.state.time=480;life.update();assert.equal(tradeWithCaravan(world,'sheep').ok,false);
assert.equal(source.resources.food,reservedFood+40);assert.equal(source.resources.sheep,reservedSheep+2);assert.equal(source.resources.silver,15);
life.update();assert.equal(source.resources.silver,15,'departure transfers initial purse and earnings once');
assert.equal(world.state.life.wolves.stage,'forecast');home.labor.defense=1;home.wood=10;home.iron=10;
assert.equal(protectHerd(world).ok,true);assert.equal(protectHerd(world).ok,false);
home.labor.husbandry=1;home.food=100;
world.state.time=600;life.update();world.state.time=630;life.update();assert.equal(world.state.life.sheep,1);
assert.ok(home.fiber>0, 'fed sheep supply fiber for weaving');
home.labor.husbandry=0;world.state.time=720;life.update();world.state.time=840;life.update();assert.equal(world.state.life.sheep,0);
assert.ok(world.state.entities.size<=9,'representatives are bounded, not one per animal');
console.log('livingWorld: passed');
