import assert from 'node:assert/strict';
import { decodeOracleIntent, oracleIntentPrompt, ORACLE_INTENT_SCHEMA } from '../src/llm/OracleIntent.js';
import { Game } from '../src/game/Game.js';
import { LocalAI } from '../src/llm/LocalAI.js';
const wire=(intent,fields={})=>({intent,value:'',amount:0,direction:'',target:'home',...fields});
assert.deepEqual(decodeOracleIntent(wire('hero_dispatch')), {status:'understood',action:'hero_dispatch',target:'home',parameters:{}});
assert.deepEqual(decodeOracleIntent(wire('produce',{value:'planks',amount:3})),{type:'order',name:'produce',recipeId:'planks',count:3});
assert.deepEqual(decodeOracleIntent(wire('dungeon_policy',{value:'hunt'})),{type:'order',name:'dungeon',operation:'policy',value:'hunt'});
assert.deepEqual(decodeOracleIntent(wire('prepare_defense',{value:'trap'})).parameters,{preparation:'trap'});
assert.equal(decodeOracleIntent(wire('create_rain',{target:'external'})).status,'unclear');
assert.equal(decodeOracleIntent(wire('none')).status,'unclear');
for(const invalid of [wire('erase_map'),wire('produce',{value:'planks',amount:21}),wire('hero_dispatch',{amount:5}),wire('hero_recall',{direction:'west'}),wire('increase_food',{amount:5000}),wire('religion_enact',{value:'unlimited_food'}),{...wire('hero_dispatch'),execute:true},wire('__proto__')])assert.equal(decodeOracleIntent(invalid),null);
const context={defaultTarget:'home',situation:{villages:[{id:'home',name:'Worldtree Settlement'}],hero:{equipment:{items:Array(200).fill('irrelevant')}},recent_events:Array(100).fill('irrelevant')}};
assert.equal(oracleIntentPrompt({message:'Send the hero to the dungeon.',...context}).includes('irrelevant'),false,'oracle classification must not serialize inventories or world history');
let calls=0;
const ai=new LocalAI();ai.session={destroy(){},clone:async()=>{let count=0;return {destroy(){},prompt:async(prompt,options)=>{calls++;assert.equal(++count,1,'each classification uses a fresh conversation');if(prompt.startsWith('Verify'))return '{"matches":true}';assert.deepEqual(options.responseConstraint,ORACLE_INTENT_SCHEMA);return JSON.stringify(wire('hero_dispatch'));}}}};
assert.equal((await ai.interpret('Send the hero to the dungeon.',context)).action,'hero_dispatch','production provider must decode the compact intent');
assert.equal(calls,2);
assert.deepEqual(decodeOracleIntent(wire('prepare_fire',{value:'trap'})).parameters,{},'irrelevant model fields cannot reach the executor');
ai.stop();
// A structurally valid but semantically wrong proposal cannot mutate the game.
const blocked=new LocalAI();let requests=0;
blocked.session={destroy(){},clone:async()=>({destroy(){},prompt:async p=>{requests++;return p.startsWith('Verify')?'{"matches":false}':JSON.stringify(wire('increase_food',{amount:50}));}})};
assert.equal((await blocked.interpret('Send the hero to the dungeon.',context)).status,'unclear');
assert.equal(requests,4,'repair is bounded and must also match');blocked.stop();
const game=new Game(null,{ritual:false});
const faith=game.world.state.faith.points,food=game.world.getVillage('home').food;
game.localAI.session={destroy(){},clone:async()=>({destroy(){},prompt:async p=>p.startsWith('Verify')?'{"matches":false}':JSON.stringify(wire('increase_food',{amount:50}))})};
assert.equal((await game.sendDivineMessage('Send the hero to the dungeon.')).ok,false);
assert.equal(game.world.getVillage('home').food,food,'mismatched action cannot grant food');
assert.equal(game.world.state.faith.points,faith,'mismatched action cannot charge faith');
game.stop();
console.log('oracleIntent: passed');
