import assert from 'node:assert/strict';
import { Game } from '../src/game/Game.js';
import { stepWorld } from '../src/game/WorldStep.js';
import { dungeonOrder, prepareDungeonRoute, dungeonEncounter } from '../src/game/Dungeon.js';
import { executeHeroOrder } from '../src/game/Hero.js';
import { autoSalvage, grantEquipment, awardEquipmentGoals, deriveHeroStats } from '../src/game/Equipment.js';
import { decodeWorld } from '../src/state/Persistence.js';
import { parseChatCommand } from '../src/game/ChatCommands.js';
import { recordEvent } from '../src/game/EventJournal.js';
import { LocalAI } from '../src/llm/LocalAI.js';
import { validOracleOrder } from '../src/llm/OracleOrders.js';
const g=new Game(null,{seed:42}),w=g.world,h=w.state.hero,home=w.getVillage('home');
Object.assign(home,{food:500,herbs:100,coal:100});
assert.ok(executeHeroOrder(w,{action:'hero_dispatch',target:'home',parameters:{}}).ok);
assert.deepEqual(h.dungeon.route.options,['normal','elite']);
assert.ok(dungeonOrder(w,{operation:'route',value:'elite'}).ok);
h.room=2;g.hero.beginEncounter();const committed=structuredClone(h.encounter);
assert.equal(committed.kind,'elite');assert.equal(dungeonOrder(w,{operation:'route',value:'normal'}).ok,false);
const faith=w.state.faith.points;assert.equal(dungeonOrder(w,{operation:'light',value:'faith'}).ok,false);assert.equal(w.state.faith.points,faith);
const restored=new Game(null,{restored:decodeWorld(g.snapshot())});assert.deepEqual(restored.world.state.hero.encounter,committed);restored.stop();
g.hero.finishEncounter();const wins=h.dungeon.eliteWins;g.hero.finishEncounter();assert.equal(h.dungeon.eliteWins,wins,'one settlement only');
h.mode='exploring';h.dungeon.light=10;const coal=home.coal;
assert.ok(dungeonOrder(w,{operation:'light',value:'coal'}).ok);assert.equal(home.coal,coal-2);assert.equal(h.dungeon.light,50);
h.dungeon.light=100;const monster={hp:26,damage:4},stats=deriveHeroStats(h);h.depth=3;h.room=3;
const bright=dungeonEncounter(h,monster,stats,0);h.dungeon.light=0;const dark=dungeonEncounter(h,monster,stats,0);
assert.equal(dark.kind,'boss');assert.ok(dark.damage>bright.damage);
assert.ok(dungeonEncounter(h,monster,{...stats,armor:stats.armor+5,damage:stats.damage+10},0).damage<dark.damage,'equipment mitigates hard-room damage');
h.dungeonsCleared=100;awardEquipmentGoals(w);assert.equal(h.equipment.goals.mythic,false,'ordinary clears do not grant boss rewards');
h.dungeon.eliteWins=3;h.dungeon.bossWins=2;awardEquipmentGoals(w);awardEquipmentGoals(w);
assert.equal(h.equipment.items.filter(i=>i.grade==='unique').length,1);assert.equal(h.equipment.items.filter(i=>i.grade==='mythic').length,1);
const keep=grantEquipment(w,'ward','common','test');keep.locked=true;
const rare=grantEquipment(w,'ward','rare','test');grantEquipment(w,'ward','common','test');
h.equipment.autoSalvage=true;home.iron=1000;assert.equal(autoSalvage(w),0);
home.iron=0;assert.ok(autoSalvage(w)>0);assert.ok(h.equipment.items.includes(keep));assert.ok(h.equipment.items.includes(rare));
h.cycleId=2;prepareDungeonRoute(h);h.room=2;h.rewardedRoom=1;h.settledIds=[];g.hero.beginEncounter();
assert.equal(h.encounter.kind,'spring');assert.equal(h.scene.monsterId,null);const xp=h.totalXp;g.hero.finishEncounter();assert.equal(h.totalXp,xp);
for(const text of ['던전 엘리트 노려','dungeon hunt','ダンジョン エリート狙い'])assert.equal(parseChatCommand(text).value,'hunt');
for(const text of ['커먼 자동 분해 켜','auto salvage common on','コモン自動分解オン'])assert.equal(parseChatCommand(text).operation,'lootPolicy');
const event={source:'world',actor:'home',action:'test',time:0};recordEvent(w.state,event);recordEvent(w.state,event);
assert.equal(w.state.recent_events.filter(e=>e.journalId===event.journalId).length,1);
assert.equal(g.worldDecisions.events.filter(e=>e.journalId===event.journalId).length,1);
const invalid=JSON.parse(g.snapshot());invalid.state.hero.dungeon.light=101;assert.throws(()=>decodeWorld(JSON.stringify(invalid)));
g.stop();
// Both real-frame and long-run clients use this exact world step.
const a=new Game(null,{seed:91}),b=new Game(null,{seed:91});
for(let n=0;n<8;n++){await stepWorld(a,1000);for(let k=0;k<4;k++)await stepWorld(b,250);}
assert.deepEqual(a.world.state,b.world.state);const paused=structuredClone(a.world.state);await stepWorld(a,0);assert.deepEqual(a.world.state,paused);a.stop();b.stop();
assert.ok(validOracleOrder({type:'order',name:'dungeon',operation:'policy',value:'hunt'}));
assert.equal(validOracleOrder({type:'order',name:'dungeon',operation:'policy',value:'hunt',target:'enemy'}),false);
const failGame=new Game(null);failGame.localAI.session={clone:async()=>({destroy(){},prompt:async()=>'{bad'})};
failGame.localAI.options.expectedInputs[0].languages=['en','ko','ja'];failGame.interpret=failGame.localAI.interpret;
const beforeFaith=failGame.world.state.faith.points;
const failure=await failGame.sendDivineMessage('Make them remember');
assert.equal(failure.ok,false);assert.equal(failGame.worldDecisions.interpretations.length,0);assert.equal(failGame.world.state.faith.points,beforeFaith);
assert.equal(failure.messageKey,'oracle.failed');
failGame.localAI.session={clone:async()=>({destroy(){},prompt:async(p)=>p.startsWith('Verify')?'{"matches":true}':JSON.stringify({intent:'dungeon_policy',value:'hunt',amount:0,direction:'',target:'home'})})};
assert.ok((await failGame.sendDivineMessage('hunt elites')).ok);assert.equal(failGame.world.state.hero.dungeon.policy,'hunt');
assert.ok(validOracleOrder({type:'order',name:'religion',operation:'accept',id:'food'}));
failGame.localAI.session=null;failGame.stop();
const ai=new LocalAI();ai.session={clone:async()=>({destroy(){},prompt:async(p)=>p.startsWith('Verify')?'{"matches":true}':JSON.stringify({intent:'dungeon_policy',value:'hunt',amount:0,direction:'',target:'home'})})};
assert.equal((await ai.interpret('hunt elites',{defaultTarget:'home'})).value,'hunt');ai.session=null;ai.stop();
console.log('remaining feedback: passed');
