import assert from 'node:assert/strict';
import { createInitialWorld } from '../src/game/World.js';
import { Factions } from '../src/game/Factions.js';
import { WorkSystem, queueConstruction } from '../src/game/Work.js';
import { LivingWorld } from '../src/game/LivingWorld.js';
import { initializeVisit, tradeBasket, setTradePolicy, updateTrade } from '../src/game/Trading.js';
import { parseChatCommand, executeChatOrder } from '../src/game/ChatCommands.js';
import { encodeWorld, decodeWorld } from '../src/state/Persistence.js';
import { I18n } from '../src/i18n/I18n.js';
import { tradeSummary } from '../src/ui/Merchant.js';
import { Game } from '../src/game/Game.js';
import { ChatCommands } from '../src/game/ChatCommands.js';
function setup(){const w=createInitialWorld();new Factions(w);new WorkSystem(w);const h=w.getVillage('home');h.silver=20;const life=new LivingWorld(w);w.state.time=240;life.update();const f=w.state.factions.find(f=>f.id===w.state.life.caravan.source);f.resources.silver=12;w.state.time=360;life.update();return {w,h,life,f,v:w.state.life.caravan};}
let {w,h,life,f,v}=setup();
const order=(lines,extra={})=>({visitId:v.id,commandId:`test:${v.revision}`,lines,...extra});
let before=encodeWorld(w);
assert.equal(tradeBasket(w,order([{side:'buy',resource:'iron',amount:100}])).code,'stock');assert.equal(encodeWorld(w),before);
assert.equal(tradeBasket(w,order([{side:'buy',resource:'food',amount:10}],{budget:1})).code,'money');
const buy=order([{side:'buy',resource:'iron',amount:3}]);assert.equal(tradeBasket(w,buy).ok,true);assert.equal(h.iron,8);assert.equal(h.silver,17);
assert.equal(tradeBasket(w,buy).code,'duplicate');assert.equal(v.cash,15);
assert.equal(tradeBasket(w,order([{side:'sell',resource:'gold',amount:1}])).code,'reserve');
assert.equal(setTradePolicy(w,{visitId:v.id,setting:'reserve',resource:'wood',value:10}).ok,true);
assert.equal(tradeBasket(w,order([{side:'sell',resource:'wood',amount:6}])).code,'reserve');
assert.equal(tradeBasket(w,order([{side:'sell',resource:'wood',amount:5},{side:'buy',resource:'herbs',amount:1}],{budget:0})).ok,true);
assert.equal(h.wood,10);assert.equal(h.herbs,5);assert.equal(h.silver,17.45);
const roundtrip=decodeWorld(encodeWorld(w)).world;assert.deepEqual(roundtrip.state.life.caravan,v);
const remaining=structuredClone(v.stock),cash=v.cash,origin=structuredClone(f.resources);w.state.time=v.departAt;life.update();
for(const [id,n]of Object.entries(remaining))assert.equal(f.resources[id],(origin[id]??0)+n);
assert.equal(f.resources.silver,origin.silver+cash);const settled=encodeWorld(w);life.update();assert.equal(encodeWorld(w),settled);
assert.equal(tradeBasket(w,buy).ok,false);
({w,h,life,f,v}=setup());h.food=0;h.herbs=0;h.wood=100;
const initial=encodeWorld(w);updateTrade(w);assert.equal(encodeWorld(w),initial,'arrival grace');
v.manualHoldUntil=400;w.state.time=380;updateTrade(w);assert.equal(v.autoCount,0,'manual instruction wins');
w.state.time=401;updateTrade(w);assert.ok(h.food>0);assert.ok(v.policy.spent<=v.policy.budget);assert.equal(v.ledger[0].automatic,true);
setTradePolicy(w,{visitId:v.id,setting:'enabled',value:false});w.state.time=450;const count=v.autoCount;updateTrade(w);assert.equal(v.autoCount,count);
({w,h,life,f,v}=setup());h.wood=60;h.stone=40;h.cloth=20;assert.equal(queueConstruction(w,{action:'build_house'}).ok,true);
assert.equal(tradeBasket(w,{visitId:v.id,commandId:'reserved',lines:[{side:'sell',resource:'wood',amount:41}]}).ok,false,'paid/reserved building resources cannot be sold');
for(const s of ['철 3 구매','buy iron 3','鉄 3 購入'])assert.deepEqual(parseChatCommand(s).lines,[{resource:'iron',amount:3,side:'buy'}]);
for(const s of ['철 3 구매하지 마','buy iron 3 unless cheap','鉄 3 購入しない'])assert.notEqual(parseChatCommand(s)?.name,'trade');
const faith=w.state.faith.points;executeChatOrder(w,{type:'order',name:'trade',visitId:v.id,commandId:'free',lines:[{side:'buy',resource:'iron',amount:1}]});assert.equal(w.state.faith.points,faith);
for(const locale of ['ko','en','ja'])assert.ok(!tradeSummary(w,v,new I18n({locale,storage:null})).includes('trade.'));
({w,h,life,f,v}=setup());h.wood=60;
assert.equal(tradeBasket(w,{visitId:v.id,commandId:'sell',lines:[{side:'sell',resource:'wood',amount:10}]}).ok,true);
assert.ok(v.earned<0);assert.equal(decodeWorld(encodeWorld(w)).world.state.life.caravan.earned,v.earned,'net outflow survives save');
const bad=JSON.parse(encodeWorld(w));bad.state.life.caravan.policy.budget=-1;assert.throws(()=>decodeWorld(JSON.stringify(bad)),/invalid_trade/);
const beforeOld=encodeWorld(w);assert.equal(tradeBasket(w,{visitId:'caravan-old',commandId:'stale',lines:[{side:'buy',resource:'food',amount:1}]}).code,'expired');assert.equal(encodeWorld(w),beforeOld);
const game=new Game(null,{restored:{world:w},ritual:false,interpret:async()=>{throw Error('management grammar must not require a model');},decideWorld:async()=>({action:'none'})});
const commands=new ChatCommands(game);w.state.faith.points=0;
const beforeIron=h.iron;assert.equal((await commands.send('철 1 구매')).ok,true);assert.equal(h.iron,beforeIron+1);assert.equal(w.state.faith.points,0);
assert.equal(v.playerDecision,'responded');
assert.equal((await commands.send('거래 중지')).ok,true);assert.equal(v.policy.enabled,false);
assert.equal((await commands.send('목재 2와약초 1 교환')).ok,false,'malformed transaction must not execute');
assert.equal(v.manualHoldUntil,0);assert.ok(game.divineHistory.some(e=>e.outcome==='applied'));
console.log('trading: passed');
