import assert from 'node:assert/strict';
import { Game } from '../src/game/Game.js';
import { LivingWorld } from '../src/game/LivingWorld.js';
import { quoteTrade, tradeBasket, tradePrice, setTradePolicy } from '../src/game/Trading.js';
import { parseTradeCommand, validTradeIntent } from '../src/game/TradeCommands.js';
import { ChatCommands } from '../src/game/ChatCommands.js';
import { LocalAI } from '../src/llm/LocalAI.js';
const g=new Game(null,{ritual:false}),w=g.world,h=w.getVillage('home');h.silver=100;h.wood=60;
const life=new LivingWorld(w);w.state.time=240;life.update();w.state.time=360;life.update();const v=w.state.life.caravan;
const command=(text,id)=>({...parseTradeCommand(text),visitId:v.id,commandId:id});
const buy=command('철 5개 사되 은 4개 넘게 쓰지 마','budget');assert.equal(buy.budget,4);
assert.equal(quoteTrade(w,buy).ok,false,'Budget cannot silently reduce the requested quantity');
const partial={...buy,commandId:'partial',partial:true};const offer=quoteTrade(w,partial);assert.ok(offer.ok);assert.ok(offer.quote.lines[0].amount<5);
const oldSilver=h.silver;assert.ok(tradeBasket(w,{...partial,quote:offer.quote}).ok);assert.equal(h.silver,oldSilver-offer.quote.debit);
assert.equal(tradeBasket(w,partial).code,'duplicate');
const forged=command('철 1 구매','forged'),q=quoteTrade(w,forged).quote;q.debit=0;
const before=JSON.stringify(w.state.life);assert.equal(tradeBasket(w,{...forged,quote:q}).code,'stale');assert.equal(JSON.stringify(w.state.life),before);
const stale=command('철 1 구매','stale'),staleQuote=quoteTrade(w,stale).quote;
assert.ok(tradeBasket(w,command('철 1 구매','other')).ok);assert.equal(tradeBasket(w,{...stale,quote:staleQuote}).code,'stale');
const expiry=command('철 1 구매','expiry'),expiryQuote=quoteTrade(w,expiry).quote;w.state.time=expiryQuote.expiresAt;
assert.equal(tradeBasket(w,{...expiry,quote:expiryQuote}).code,'stale');w.state.time=360;
v.cash=100;
assert.ok(tradeBasket(w,command('나무는 30개 남기고 팔아','surplus')).ok);assert.equal(h.wood,30);assert.equal(v.policy.reserves.wood,30);
const forbid=command('약초와 금은 팔지 마','forbid');assert.ok(validTradeIntent(forbid));assert.ok(setTradePolicy(w,forbid).ok);assert.ok(v.policy.forbidden.includes('herbs'));
assert.ok(setTradePolicy(w,command('식량 부족분만 알아서 사','essential')).ok);assert.equal(v.policy.only,'food');
assert.ok(setTradePolicy(w,command('거래 중지','stop')).ok);assert.equal(tradeBasket(w,command('철 1 구매','stopped')).code,'stopped');
for(const text of ['철 50 구매 가능한 만큼','buy iron 50 as much as possible','鉄 50 購入 できるだけ'])assert.equal(parseTradeCommand(text).partial,true);
for(const text of ['sell surplus wood keeping 30','木材を30残して売って'])assert.equal(parseTradeCommand(text).surplus.retain,30);
for(const text of ['never sell herbs and gold','薬草と金を売らない'])assert.equal(parseTradeCommand(text).resources.length,2);
assert.equal(tradePrice('iron','buy',{specialty:'iron',relationFactor:0.95,initialStock:{iron:8},stock:{iron:0}}),0.94);
assert.ok(tradePrice('iron','sell',v)<tradePrice('iron','buy',v));
const ai=new LocalAI();ai.session={clone:async()=>({prompt:async()=>JSON.stringify({type:'order',name:'trade',lines:[{side:'buy',resource:'iron',amount:2}],budget:3}),destroy(){}}),destroy(){}};
ai.options.expectedInputs[0].languages=['en','ko','ja'];
for(const text of ['상인에게 철 두 개를 사줘','Please purchase two iron','鉄を二個買って'])assert.ok(validTradeIntent(await ai.interpretTrade(text)));
ai.session.clone=async()=>({prompt:async()=>JSON.stringify({type:'order',name:'trade',lines:[{side:'buy',resource:'iron',amount:-1}]}),destroy(){}});
assert.equal((await ai.interpretTrade('buy iron 1')).type,'invalid','Malformed model output cannot execute a fallback trade');
// Late interpretation cannot bind a new visitor, even with matching inventory.
const chats=new ChatCommands(g);let release;g.localAI.interpretTrade=()=>new Promise(resolve=>{release=resolve;});
const pending=chats.send('Please purchase a little iron');assert.ok(v.manualHoldUntil>w.state.time);
w.state.life.caravan={...v,id:'caravan-next'};release({type:'order',name:'trade',lines:[{side:'buy',resource:'iron',amount:1}]});
assert.equal((await pending).messageKey,'trade.expired');
ai.stop();g.stop();
console.log('tradeConditions: passed (quotes, partial fills, policies, multilingual fallback/model and stale visits)');
